### ISSUE TITLE
Tensorflow limitations on GPU

### ISSUE THREAD

**Issue by apoorva-ovgu** [apoorva-ovgu/ProteinIdentificationGPU#1]
By Gabriel 12.09.2017:
![matrixtracenotworkingongpus](https://user-images.githubusercontent.com/19211975/30331556-70ae8ef8-97d8-11e7-8bae-5aa25abbc710.png)
I also want to report that I was not able to run the distributed...py matrix examples, because the GPU did not support the call to trace (see screenshot attached).

**Comment by apoorva-ovgu** [comment]
A common workaround is by executing:

config = tf.ConfigProto(allow_soft_placement = True)
sess = tf.Session(config = config)


This automatically chooses the available device, thereby eliminating configuration issues.

**Comment by gabrielcc2** [comment]
Ok. Thanks for the pointer :+1: 

I think that it'll be good to keep alert, as we move forward, on what is actually supported on the GPU, and what is not. I guess it'll be some kind of trial and error...
